version: '2'
services:

 rabbitmq:
  image: marcelmaatkamp/rabbitmq-mqtt-ldap
  restart: always
  hostname: rabbitmq
  ports:
   - 5671:5671
   - 15673:15672
  environment:
   - RABBITMQ_NODENAME=rabbitmq@rabbitmq
  volumes:
   - rabbitmq:/var/lib/rabbitmq/mnesia

 java:
  image: java/example
  build:
   context: .
  ports:
   - "8080:8080"
  volumes:
   - ./application:/application
   - gradle:/root/.gradle
   - gradle:/application/.gradle

 smb:
  image: grossws/smbd
  restart: "always"
  ports:
   - 445:445
  volumes:
   - ./application:/data

volumes:
 rabbitmq:
 gradle:
