version: '3'
services:

 rabbitmq:
  image: marcelmaatkamp/rabbitmq-mqtt-ldap
  restart: always
  hostname: rabbitmq
  ports:
   - 5671:5671
   - 15673:15672
  environment:
   - RABBITMQ_NODENAME=rabbitmq@rabbitmq
  volumes:
   - rabbitmq:/var/lib/rabbitmq/mnesia

 demo:
  image: java/example
  build:
   context: .
  ports:
   - "8080:8080"
  volumes:
   - ./application/demo:/application
   - gradle:/root/.gradle
   - gradle:/application/.gradle

 registry:
  image: java/example
  build:
   context: .
  ports:
   - "8081:8080"
  volumes:
   - ./application/registry_server:/application
   - gradle:/root/.gradle
   - gradle:/application/.gradle

 rxjava-processor:
  build:
   context: .
   dockerfile: dockerfiles/spring-cloud-stream-samples/rxjava-processor/Dockerfile
  command: mvn spring-boot:run
  volumes:
   - maven:/root/.m2
   - ./spring-cloud-stream-samples:/application

 smb:
  image: grossws/smbd
  restart: "always"
  ports:
   - 445:445
  volumes:
   - ./application:/data

volumes:
 rabbitmq:
 gradle:
 maven: 
